const sportExercises = [
  { id: 1,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: 'Biceps',
    secondary_muscles: '',
    description: `Stand around 30 - 40cm away from the cable, the feet are
     firmly on the floor. Take the bar and lift the weight with a fast movements.
     Lower the weight as with the dumbbell curls slowly and controlled.`,
    comments: `Don't move the elbows during the exercise`,
    gif: 'http://rs1074.pbsrc.com/albums/w415/cherokeehackslife/Workout%20Gifs/Bicep-Curl---Cables.gif~c200',
    video: ''
  },
  { id: 2,
    exercise: 'Biceps Curls With Barbell',
    category: 'Arms',
    main_muscles: 'Biceps',
    secondary_muscles: '',
    description: `Hold the Barbell shoulder-wide, the back is straight, the shoulders
     slightly back, the arms are streched. Bend the arms, bringing the weight up, with a
      fast movement. Without pausing, let down the bar with a slow and controlled movement.
    Don't allow your body to swing during the exercise, all work is done by the biceps,
     which are the only mucles that should move (pay attention to the elbows).`,
    comments: `Keep your upper body straight
    Fluid movements with no pauses at the top or the bottom`,
    gif: 'https://i.makeagif.com/media/11-07-2015/P7PT43.gif',
    video: ''
  },
  { id: 3,
    exercise: 'Hammercurls',
    category: 'Arms',
    main_muscles: 'Biceps',
    secondary_muscles: '',
    description: `Hold two dumbbells and sit on a bench with a straight back,
     the shoulders are slightly rolled backwards. Your pals point to your
      body. Bend the arms and bring the weight up with a fast movement.
       Don't rotate your hands, as with the curls. Without any pause bring 
       the dumbbell down with a slow, controlled movement.
    Don't swing your body during the exercise, the biceps should 
    do all the work here. The elbows are at your side and don't move.`,
    comments: `Keep the elbows right next to the body and don't move them`,
    gif: 'https://thumbs.gfycat.com/AlarmingVeneratedFawn-small.gif',
    video: ''
  },
  { id: 4,
    exercise: 'Dips',
    category: 'Arms',
    main_muscles: 'Triceps',
    secondary_muscles: 'Chest , Abs',
    description: `Hold onto the bars at a narrow place (if they are not
       parallel) and press yourself up, but don't stretch the arms completely,
        so the muscles stay during the whole exercise under tension. 
        Now bend the arms and go down as much as you can, keeping the elbows 
        always pointing back, 
    At this point, you can make a short pause before repeating the movement.`,
    comments: `Don't stretch your amrs completly`,
    gif: '',
    video: ''
  },
  { id: 5,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 6,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 7,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 8,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 9,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 10,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 11,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 12,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 13,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 14,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 15,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 16,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 17,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 18,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 19,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 20,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 21,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 22,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 23,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 24,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 25,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 26,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 27,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 28,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 29,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 30,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 31,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 32,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 33,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 34,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 35,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 36,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 37,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 38,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 39,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 40,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 41,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 42,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 43,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  },
  { id: 44,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    main_muscles: '',
    secondary_muscles: '',
    description: ``,
    comments: ``,
    gif: '',
    video: ''
  }
]