const sportExercises = [
  { id: 1,
    exercise: 'Biceps Curl With Cable',
    category: 'Arms',
    description: `Stand around 30 - 40cm away from the cable, the feet are
     firmly on the floor. Take the bar and lift the weight with a fast movements.
     Lower the weight as with the dumbbell curls slowly and controlled.`,
    comments: `Don't move the elbows during the exercise`,
    gif: '',
    video: ''
  },
  { id: 2,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 3,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 4,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 5,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 6,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 7,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 8,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 9,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 10,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 11,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 12,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 13,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 14,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 15,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 16,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 17,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 18,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 19,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 20,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 21,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 22,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 23,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 24,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 25,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 26,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 27,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 28,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 29,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 30,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 31,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 32,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 33,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 34,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 35,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 36,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 37,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 38,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 39,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 40,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 41,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 42,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 43,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  },
  { id: 44,
    exercise: 'Biceps Curl With Cable',
    body_part: 'Arms',
    description: '',
    comments: '',
    gif: '',
    video: ''
  }
]